#:schema node_modules/wrangler/config-schema.json
name = "probi-oh-api"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "probi-oh-db"
database_id = "84bff434-14b2-4626-9c00-0a6a1ead11ed"
